# 5. Referral Analysis

This section evaluates the effectiveness of NaijaCart's referral programme by analysing referral-generated revenue and the performance of referring customers.

---

## Referral Revenue

### Business Question

How much revenue was generated by customers acquired through referrals?

### SQL Query

```sql
SELECT
    SUM(CAST(o.Quantity AS BIGINT) * p.Price) AS Total_Referral_Revenue
FROM Customers AS c
INNER JOIN Orders AS o
    ON c.CustomerID = o.CustomerID
LEFT JOIN Products AS p
    ON o.ProductID = p.ProductID
WHERE c.ReferralCustomerID IS NOT NULL;
```

---

## Top Referrers by Referral Revenue

### Business Question

Which referrers generated the highest downstream revenue from the customers they referred?

### SQL Query

```sql
SELECT TOP 10
    r.CustomerID AS ReferrerID,
    CONCAT(r.FirstName, ' ', r.LastName) AS Full_Name,
    COALESCE(SUM(CAST(p.Price AS BIGINT) * o.Quantity), 0) AS Revenue_From_Referees
FROM Customers AS r
LEFT JOIN Customers AS c
    ON c.ReferralCustomerID = r.CustomerID
LEFT JOIN Orders AS o
    ON c.CustomerID = o.CustomerID
LEFT JOIN Products AS p
    ON o.ProductID = p.ProductID
GROUP BY
    r.CustomerID,
    CONCAT(r.FirstName, ' ', r.LastName)
ORDER BY Revenue_From_Referees DESC;
```

> **Note:** `COALESCE()` ensures that referrers without downstream purchases are displayed with a revenue value of **0** instead of `NULL`.

---

## Referral Programme Effectiveness

### Business Question

Did referred customers generate more business value than organically acquired customers?

> ** The referral program does not attract high-value customers than organically acquired customers, and here is why;
      - The combined revenue from customers acquired through one referrer is lower than the revenue generated by an individual organic customer. 
      - Only three referrers (C02,C167,C207) produced a total downstream referral revenue that exceeded the highest revenue generated by a non-referred customer (C271).**
